name: Update README 

on:
  push:
    paths:
      - 'user_action.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README using Python
        run: |
          python - <<'EOF'
          import re

          # Read file contents
          with open('README.md', 'r', encoding='utf-8') as f:
              readme_content = f.read()
          with open('user_action.yml', 'r', encoding='utf-8') as f:
              user_action_content = f.read()

          # Define pattern to replace content between sections
          pattern = r'(## Quick Start\s*\n)(.*?)(?=## Setup Instructions)'
          replacement = (
              r'\1\nAdd this workflow to your repository:\n\n'
              '```yaml\n' + user_action_content + '\n```\n\n'
          )

          # Replace content using regular expressions
          new_readme = re.sub(pattern, replacement, readme_content, flags=re.DOTALL)

          # Save changes to README.md
          with open('README.md', 'w', encoding='utf-8') as f:
              f.write(new_readme)
          EOF

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "plexicus@plexicus.com"
          git config --local user.name "Plexicus"
          git add README.md
          git commit -m "docs: update README with latest user_action.yml example"
          git push
