name: Update README
on:
  push:
    paths:
      - 'user_action.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true         # Preserve credentials for git push
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GITHUB_TOKEN

      - name: Update README
        run: |
          # Read the content of user_action.yml
          USER_ACTION_CONTENT=$(cat user_action.yml)
          
          # Create a properly formatted markdown snippet with YAML syntax highlighting
          REPLACEMENT=$'```yaml\n'"$USER_ACTION_CONTENT"$'\n```'
          
          # Use awk to replace the content between "## Quick Start" and "## Setup Instructions"
          awk -v replacement="$REPLACEMENT" '
          /^## Quick Start/{
            print;
            print "\nAdd this workflow to your repository:\n";
            print replacement;
            in_section=1;
            next;
          }
          /^## Setup Instructions/{
            in_section=0;
          }
          !in_section {
            print;
          }
          ' README.md > README.md.tmp
          
          mv README.md.tmp README.md

      - name: Check for changes
        id: git-check
        run: |
          # Check if there are changes in README.md
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          # Configure git user
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add changes
          git add README.md
          
          # Commit changes with a message
          git commit -m "docs: update README with latest user_action.yml example"
          
          # Push changes back to the repository
          git push
