name: Update README 

on:
  push:
    paths:
      - 'user_action.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README using Python
        run: |
          python - <<'EOF'
          # Read the contents of the files
          start_marker = "## Quick Start"
          end_marker = "## Setup Instructions"

          with open('README.md', 'r', encoding='utf-8') as f:
              lines = f.readlines()
          with open('user_action.yml', 'r', encoding='utf-8') as f:
              user_action_content = f.read()

          output_lines = []
          in_replacement = False

          for line in lines:
              if line.startswith(start_marker):
                  # Write the start marker and add new content
                  output_lines.append(line)
                  output_lines.append("\nAdd this workflow to your repository:\n\n```yaml\n")
                  output_lines.append(user_action_content)
                  output_lines.append("\n```\n\n")
                  in_replacement = True
              elif line.startswith(end_marker):
                  in_replacement = False
                  output_lines.append(line)
              elif not in_replacement:
                  output_lines.append(line)

          with open('README.md', 'w', encoding='utf-8') as f:
              f.writelines(output_lines)
          EOF

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "plexicus@plexicus.com"
          git config --local user.name "Plexicus"
          git add README.md
          git commit -m "docs: update README with latest user_action.yml example"
          git push
