name: Update README 

on:
  push:
    paths:
      - 'user_action.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: |
          # Leer el contenido de user_action.yml
          USER_ACTION_CONTENT=$(cat user_action.yml)
          # Usar perl para reemplazar la sección entre "## Quick Start" y "## Setup Instructions"
          perl -0777 -pe 's/(## Quick Start\s*\n)(.*?)(?=## Setup Instructions)/$1\nAdd this workflow to your repository:\n\n```yaml\n'"$USER_ACTION_CONTENT"'\n```\n\n/' README.md > README.md.tmp
          mv README.md.tmp README.md

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "plexicus@plexicus.com"
          git config --local user.name "Plexicus"
          git add README.md
          git commit -m "docs: update README with latest user_action.yml example"
          git push
